name: 'integration_tests'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'integration_tests_snowflake'

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]

seeds:  
  integration_tests:  
    +quote_columns: false

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"



